import time as t
print(t.time()) # returns no of sec from jan 1 2017
print(t.localtime())
print(t.asctime())
print(t.gmtime())
print(t.strftime('%y-%m-%d:%H-%M-%S'))
print(t.strftime('%y'))
print(t.strftime('%Y'))
print(t.strftime('%m'))
print(t.strftime('%M'))
print(t.strftime('%d'))
print(t.strftime('%D'))
print(t.strftime('%H'))
print(t.strftime('%h'))
print(t.strftime('%S'))
